# Find OpencCV
#
# OpencCV_INCLUDE_DIRS
# OpencCV_LIBRARIES
# OpencCV_FOUND
#
# OpencCV_${COMPONENT}_INCLUDE_DIR
# OpencCV_${COMPONENT}_LIBRARY
# OpencCV_VERSION
#

SET(OpencCV_COMPONENTS
    calib3d
    #contrib
    core
    features2d
    flann
    #gpu
    highgui
    imgproc
    #legacy
    ml
    objdetect
    ts
    video
    videoio
    videostab
    imgcodecs
    )

FOREACH(COMPONENT ${OpencCV_COMPONENTS})
    STRING(TOLOWER ${COMPONENT} LOWERCOMPONENT)
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

    FIND_PATH(OpencCV_${UPPERCOMPONENT}_INCLUDE_DIR NAMES opencv/cv.h)

    FIND_LIBRARY(OpencCV_${UPPERCOMPONENT}_LIBRARY NAMES opencv_${LOWERCOMPONENT})

    SET(${OpencCV_${UPPERCOMPONENT}_FOUND} 1)

    MARK_AS_ADVANCED(OpencCV_${UPPERCOMPONENT}_INCLUDE_DIR OpencCV_${UPPERCOMPONENT}_LIBRARY OpencCV_${UPPERCOMPONENT}_FOUND)
ENDFOREACH(COMPONENT)

IF(NOT OpencCV_FIND_COMPONENTS)
    SET(OpencCV_FIND_COMPONENTS ${OpencCV_COMPONENTS})
ENDIF(NOT OpencCV_FIND_COMPONENTS)

SET(OpencCV_FOUND "YES")
FOREACH(COMPONENT ${OpencCV_FIND_COMPONENTS})
    STRING(TOLOWER ${COMPONENT} LOWERCOMPONENT)
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    IF(OpencCV_${UPPERCOMPONENT}_LIBRARY AND OpencCV_${UPPERCOMPONENT}_INCLUDE_DIR)
        LIST(APPEND OpencCV_LIBRARIES ${OpencCV_${UPPERCOMPONENT}_LIBRARY})
        LIST(APPEND OpencCV_INCLUDE_DIRS ${OpencCV_${UPPERCOMPONENT}_INCLUDE_DIR})
        MESSAGE(STATUS "found lib${LOWERCOMPONENT}: -I${OpencCV_${UPPERCOMPONENT}_INCLUDE_DIR}, ${OpencCV_${UPPERCOMPONENT}_LIBRARY}")
    ELSE(OpencCV_${UPPERCOMPONENT}_LIBRARY AND OpencCV_${UPPERCOMPONENT}_INCLUDE_DIR)
        #SET(OpencCV_FOUND "NO")
        IF(OpencCV_FIND_REQUIRED)
            MESSAGE(STATUS "Beware: opencv component ${LOWERCOMPONENT} NOT found")
        ELSE(OpencCV_FIND_REQUIRED)
            MESSAGE(STATUS "opencv component ${LOWERCOMPONENT} NOT found")
        ENDIF(OpencCV_FIND_REQUIRED)
    ENDIF(OpencCV_${UPPERCOMPONENT}_LIBRARY AND OpencCV_${UPPERCOMPONENT}_INCLUDE_DIR)
ENDFOREACH(COMPONENT)

IF(OpencCV_INCLUDE_DIRS)
    LIST(REMOVE_DUPLICATES OpencCV_INCLUDE_DIRS)
ENDIF(OpencCV_INCLUDE_DIRS)

MARK_AS_ADVANCED(OpencCV_LIBRARIES OpencCV_INCLUDE_DIRS OpencCV_FOUND)
